CREATE INDEX "event_attendees_event_id_idx" ON "event_attendees" USING btree ("event_id");--> statement-breakpoint
CREATE INDEX "event_tasks_event_id_idx" ON "event_tasks" USING btree ("event_id");--> statement-breakpoint
CREATE POLICY "event_attendees_select_owner_or_collaborator" ON "event_attendees" AS PERMISSIVE FOR SELECT TO "authenticated" USING (public.is_event_owner("event_attendees"."event_id", (select auth.uid())) OR public.is_event_collaborator("event_attendees"."event_id", (select auth.uid())));--> statement-breakpoint
CREATE POLICY "event_attendees_insert_owner_or_editor" ON "event_attendees" AS PERMISSIVE FOR INSERT TO "authenticated" WITH CHECK (public.is_event_owner("event_attendees"."event_id", (select auth.uid())) OR public.is_event_collaborator("event_attendees"."event_id", (select auth.uid()), 'editor'));--> statement-breakpoint
CREATE POLICY "event_attendees_update_owner_or_editor" ON "event_attendees" AS PERMISSIVE FOR UPDATE TO "authenticated" USING (public.is_event_owner("event_attendees"."event_id", (select auth.uid())) OR public.is_event_collaborator("event_attendees"."event_id", (select auth.uid()), 'editor'));--> statement-breakpoint
CREATE POLICY "event_attendees_delete_owner_or_editor" ON "event_attendees" AS PERMISSIVE FOR DELETE TO "authenticated" USING (public.is_event_owner("event_attendees"."event_id", (select auth.uid())) OR public.is_event_collaborator("event_attendees"."event_id", (select auth.uid()), 'editor'));--> statement-breakpoint
CREATE POLICY "event_tasks_select_owner_or_collaborator" ON "event_tasks" AS PERMISSIVE FOR SELECT TO "authenticated" USING (public.is_event_owner("event_tasks"."event_id", (select auth.uid())) OR public.is_event_collaborator("event_tasks"."event_id", (select auth.uid())));--> statement-breakpoint
CREATE POLICY "event_tasks_insert_owner_or_editor" ON "event_tasks" AS PERMISSIVE FOR INSERT TO "authenticated" WITH CHECK (public.is_event_owner("event_tasks"."event_id", (select auth.uid())) OR public.is_event_collaborator("event_tasks"."event_id", (select auth.uid()), 'editor'));--> statement-breakpoint
CREATE POLICY "event_tasks_update_owner_or_editor" ON "event_tasks" AS PERMISSIVE FOR UPDATE TO "authenticated" USING (public.is_event_owner("event_tasks"."event_id", (select auth.uid())) OR public.is_event_collaborator("event_tasks"."event_id", (select auth.uid()), 'editor'));--> statement-breakpoint
CREATE POLICY "event_tasks_delete_owner_or_editor" ON "event_tasks" AS PERMISSIVE FOR DELETE TO "authenticated" USING (public.is_event_owner("event_tasks"."event_id", (select auth.uid())) OR public.is_event_collaborator("event_tasks"."event_id", (select auth.uid()), 'editor'));